# Custom Language File for Launcher Customizer

[ejs.app]
title = "수달이네마을2"

[ejs.landing]
mediaGitHubURL = "https://github.com/CustomLauncherLab/sudaltown"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/sudaltown"
supportLink = "https://github.com/CustomLauncherLab/sudaltown/issues"

[ejs.welcome]
welcomeHeader = "수달이네마을2"
welcomeDescription = ""
welcomeDescCTA = "계속하기 버튼을 눌러 계속 진행하여 주세요."
